modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
logoFile="logo.png"
logoBlur=false
[[mods]]
   modId="${mod_id}"
   version="${mod_version}"
   displayName="${mod_name}"
   authors="${mod_authors}"

description='''${mod_description}'''
[[dependencies."${mod_id}"]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version}"
   ordering="NONE"
   side="BOTH"


[[dependencies."${mod_id}"]]
   modId="mekanism"
   mandatory=false
   versionRange="[10.4.7, )"
   ordering="AFTER"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId="create"
   mandatory=false
   versionRange="[6.0.1, )"
   ordering="AFTER"
   side="BOTH"